### ISSUE TITLE
关于文章超参数设置的询问

### ISSUE THREAD

**Issue by study-gl** [ShenzhiYang2000/NODESAFE-Bounded-and-Uniform-Energy-based-Out-of-distribution-Detection-for-Graphs#1]
尊敬的作者：
        您好，感谢您精彩的工作和提供的原始代码。我在复现文章结果时，遇到了一些问题，期待您的回复。
即：在使用了run.sh中提供的命令去实现Cora-structure在无OOD暴露下的设置：python main.py --method nodesafe --backbone gcn --dataset cora --ood_type structure --mode detect --use_bn --use_prop --use_UB --device 0 --lamda2 12。
运行的最后结果： **AUROC：74.16， AUPR：47.46， FPR95: 80.54。**

对于cora-label和Twitch数据集在默认参数下也出现了类似的问题。下面是我的参数：
**Cora-structure:** 
Namespace(K=2, T=1.0, alpha=1.0, backbone='gcn', cached=False, cpu=False, data_dir='../data/', dataset='cora', device=0, display_step=1, dropout=0.5, epochs=200, eta=0.5, gat_heads=8, hidden_channels=64, hops=2, lamda1=0.999, lamda2=12.0, lr=0.01, m_in=-5, m_out=-1, method='nodesafe', mode='detect', noise=0.0, num_layers=2, ood_type='structure', out_heads=1, print_args=False, print_prop=False, runs=1, seed=123, train_prop=0.1, use_UB=True, use_bn=True, use_prop=True, use_reg=False, valid_prop=0.1, weight_decay=0.01)
ind dataset cora: all nodes 2708 | centered nodes 2708 | edges 10556 | classes 7 | feats 1433
ood tr dataset cora: all nodes 2708 | centered nodes 2708 | edges 6680
ood te dataset cora: all nodes 2708 | centered nodes 2708 | edges 6696

**Twitch**
Namespace(K=2, T=1.0, alpha=1.0, backbone='gcn', cached=False, cpu=False, data_dir='../data/', dataset='twitch', device=0, display_step=1, dropout=0.5, epochs=200, eta=0.5, gat_heads=8, hidden_channels=64, hops=2, lamda1=0.999, lamda2=1.0, lr=0.01, m_in=-5, m_out=-1, method='nodesafe', mode='detect', noise=0.0, num_layers=2, ood_type='structure', out_heads=1, print_args=False, print_prop=False, runs=1, seed=123, train_prop=0.1, use_UB=True, use_bn=True, use_prop=True, use_reg=False, valid_prop=0.1, weight_decay=0.01)
ind dataset twitch: all nodes 9498 | centered nodes 9498 | edges 315774 | classes 2 | feats 128
ood tr dataset twitch: all nodes 7126 | centered nodes 7126 | edges 77774
ood te dataset 0 twitch: all nodes 4648 | centered nodes 4648 | edges 123412
ood te dataset 1 twitch: all nodes 6551 | centered nodes 6551 | edges 231883
ood te dataset 2 twitch: all nodes 4385 | centered nodes 4385 | edges 78993

请问是否我的参数设置有误？期待您的回复，祝好！

**Comment by ShenzhiYang2000** [comment]
您好，十分感谢关注我们的工作，经过检查，是由于loss.py文件和nodesafe.py文件出现了纰漏，现已订正。
![cora-f-1](https://github.com/user-attachments/assets/0e84983c-b063-468f-b211-f919694b3370)
![cora-f-2](https://github.com/user-attachments/assets/c0908de8-31c0-4b86-a469-5d31367b2333)
![cora-s-1](https://github.com/user-attachments/assets/c31c8cc0-9bc4-4e58-a7f4-e9fd9554b660)
![cora-s-2](https://github.com/user-attachments/assets/b3dfc413-567e-4197-b475-d051dc63a5c4)
再次感谢，我们将继续完善这份代码，如果有任何问题，please feel free to contact us！😀
